---

PG_packages:
  - postgresql96-server
  - postgresql96-contrib
  - postgresql96-libs
  - postgresql96-python
  - pgbouncer
  - repmgr96
  - pgbadger
  - barman
  - barman-cli
  - bzip2
  - gzip
  - xz
  - logrotate

postgres_user: postgres

created_users:
  - name: barman
    password: barman_123
    roles: REPLICATION,SUPERUSER
  - name: repmgr
    password: repmgr_123
    roles: REPLICATION
  - name: maas_admin
    password: maas_admin_123
    roles: CREATEDB,NOSUPERUSER
