---

- name: casandra rolling restart
  hosts: cassandra
  remote_user: jonyc
  serial: 1
  become: yes
  become_user: root
  tasks:
      # place db into backup mode
    - name: clear the node and drain
      command: nodetool disablegossip ; nodetool disablebinary ; nodetool disablethrift ; nodetool drain ;
    - service:
        name: cassandra
        state: restarted
    # wait until the string "completed" is in the file /tmp/foo before continuing
    - name: wait for normal state
      wait_for:
        path: /var/log/cassandra/system.log
        search_regex:  state jump to NORMAL
    - name: clear the node and drain
      command: nodetool disablegossip ; nodetool disablebinary ; nodetool disablethrift ; nodetool drain ;
    - shell: /usr/bin/uptime
      register: result

    - debug:
        var: result
        verbosity: 1