---
- hosts: all
  remote_user: jonyc
  gather_facts: no
  vars:
    region: us-west-1
    instance_type: r4.2xlarge
    profile: production_96
  tasks:
    # - name: get instance id
    #   uri:
    #     url: http://169.254.169.254/latest/meta-data/instance-id
    #     return_content: yes
    #   register: instance_id
    - name: get instance id
      shell:  curl -sG http://169.254.169.254/latest/meta-data/instance-id
      register: instance_id
    - name: stop instance
      ec2:
        instance_ids: '{{ instid }}'
        region: '{{ region }}'
        state: stopped
        profile: '{{ profile }}'
        wait: True
      delegate_to: 127.0.0.1
    - name: change the type
      ec2_type:
        region: '{{ region }}'
        profile: '{{ profile}}'
        id: '{{ instid }}'
        type: '{{ totype }}'
      delegate_to: 127.0.0.1
    - name: Start the sandbox instances
      ec2:
        instance_ids: '{{ instid }}'
        region: '{{ region }}'
        profile: '{{ profile }}'
        state: running
        wait: True
        instance_type: '{{ totype }}'
      delegate_to: 127.0.0.1
