# - hosts: localhost
#   connection: local
#   gather_facts: False
#   vars:
#     region: eu-central-1
#   tasks:
#     - name: spin up mongo replica hosts
#       ec2:
#         aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
#         aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
#         key_name: mgmt-eu
#         group_id: ['sg-066df76e','sg-a06d28c8']
#         count: 3
#         region: "{{ region }}"
#         instance_type: t2.medium
#         image: ami-39946a56
#         wait: yes
#         wait_timeout: 500
#         instance_tags:
#           db: mongo
#           Name: MNG-Jony
#         volumes:
#           - device_name: /dev/sdb
#             volume_size: 50
#             delete_on_termination: true
#         monitoring: no
#         vpc_subnet_id: subnet-32d23f48
#         assign_public_ip: yes
#       register: ec2
#
#     - name: print instance info
#       action: debug msg="Instance info  {{ ec2 }}"
#
#     - name: Add new instance to host group
#       add_host: name={{ item.private_ip }} groupname=mngl
#       with_items: '{{ec2.instances}}'
#
#     - name: Add one host as the "master"
#       add_host: hostname={{ item.private_ip }} groupname=mongo_master
#       with_items: '{{ ec2.instances }}'
#       run_once: true
#
#     - name: Wait for SSH to come up
#       wait_for: host={{ item.private_ip }} port=22 delay=60 timeout=320 state=started
#       with_items: '{{ec2.instances}}'
#
#     - debug: msg={{ item }}
#       with_items: "{{ groups['mngl'] }}"
#
#     # - set_fact: mongodb_login_host="{{ ec2.instances[0].private_ip }}"

- hosts: tag_global_id_{{farm_name}}_mongo
  name: deploy
  user: centos
  gather_facts: true
  vars:
    # It's a 'master' node
    mongodb_login_host: "{{ groups['tag_global_id_'+farm_name+'_mongo'][0] }}"
  roles:
    - {role: common, become: yes, become_user: root, io_sched: noop, io_rh: 32 , thp_policy: never}
    - {role: mongod,become: yes, become_user: root, tags: [mongo]}
