---
# file: postgresql.yml
# - hosts: postgres
# run: ansible-playbook -i inventories/ec2.py -e farm_name=PavelTest postgresql-deploy.yml
#

- hosts: tag_global_id_{{farm_name}}_postgres
  tags: ['master']
  remote_user: centos
  vars_files:
    - group_vars/PG-Master
  environment: "{{pg_env}}"
  roles:
    - { role: common, become: yes, become_user: root}
    - { role: PG, master: yes}
    - { role: ansible-repmgr , become: yes, become_user: root}

- include: postgresql-barman.yml
  tags: ['barman']

- include: postgresql-backup.yml
  tags: [replica]
