---
# file: postgresql-barman.yml
# - hosts: postgres
# run: ansible-playbook -i inventories/ec2.py -e farm_name=PavelTest postgresql-barman.yml
#

- hosts: tag_global_id_{{farm_name}}_barman
  tags: ['barman']
  remote_user: centos
  vars_files:
    - group_vars/tag_Role_PG_Barman
  roles:
    - { role: common, become: yes, become_user: root}
    - { role: ansible-barman , become: yes, become_user: root}
