---
# run: ansible-playbook -i inventories/ec2.py -e farm_name=PavelTest Vertica-deploy.yml

- hosts: tag_global_id_{{farm_name}}_vertica
  name: deploy
  user: centos
  vars_files:
    - group_vars/vrtl
  gather_facts: true
  vars:
    vertica_database_name: CIDB2
    vertica_package_location: /tmp/vertica-7.2.3-0.x86_64.RHEL6.rpm
  roles:
    - {role: common,
      become: yes, become_user: root,
      tags: [host]}
    - {role: ansible-vertica,
      vertica_group: "{{ groups['tag_global_id_'+farm_name+'_vertica'] }}",
      vertica_cluster: "{{ groups['tag_global_id_'+farm_name+'_vertica'] }}",
      become: yes, become_user: root,
      tags: [vertica]}
    - vertica
