---
# - hosts: localhost
#   connection: local
#   gather_facts: False
#   vars:
#     region: eu-central-1
#
#   tasks:
#     - name: spin up replica host
#       ec2:
#         aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
#         aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
#         key_name: mgmt-eu
#         group_id: ['sg-066df76e','sg-a06d28c8']
#         count: 3
#         region: "{{ region }}"
#         instance_type: m4.4xlarge
#         image: ami-39946a56
#         wait: yes
#         wait_timeout: 500
#         instance_tags:
#           db: Vertica
#           role: vertica
#           Name: VRT-Jony
#         volumes:
#           - device_name: /dev/sdb
#             volume_size: 50
#             delete_on_termination: true
#         monitoring: no
#         vpc_subnet_id: subnet-32d23f48
#         assign_public_ip: yes
#       register: ec2
#
#     - name: print instance info
#       action: debug msg="Instance info  {{ ec2.instances }}"
#
#
#     - name: Add new instance to host group
#       add_host: name={{ item.private_ip }} groups=vrtl
#       with_items: "{{ ec2.instances }}"
#
#     - name: Wait for SSH to come up
#       wait_for: host={{ item.public_ip }} port=22 delay=60 timeout=320 state=started
#       with_items: '{{ec2.instances}}'
#
#     - debug: msg={{ item }}
#       with_items: "{{ groups['vrtl'] }}"


- hosts: tag_global_id_{{farm_name}}_vertica
  name: deploy
  user: centos
  gather_facts: true
  vars:
    vertica_database_name: CIDB2
    vertica_package_location: /tmp/vertica-7.2.3-0.x86_64.RHEL6.rpm
  roles:
    - {role: common,
      become: yes, become_user: root,
      tags: [host]}
    - {role: ansible-vertica,
      vertica_group: "{{ groups['tag_global_id_'+farm_name+'_vertica'] }}",
      vertica_cluster: "{{ groups['tag_global_id_'+farm_name+'_vertica'] }}",
      become: yes, become_user: root,
      tags: [vertica]}
    - vertica
