- name: change compatibilty
  shell:  "mongo --quiet {{ansible_ssh_host}} -u {{ root_user }} -p {{ root_pass }} --authenticationDatabase admin --eval 'db.adminCommand({ setFeatureCompatibilityVersion: '\"'{{ version | regex_replace('.'+version.split('.')[-1],'') }}'\"' } )'"


- name: change compatibilty
  shell:  mongo --quiet {{ansible_ssh_host}} -u {{ root_user }} -p {{ root_pass }} --authenticationDatabase admin --eval 'cfg=rs.conf();cfg.members.forEach( function (d) { print(d.tags["version"]="{{ version}}")});rs.reconfig(cfg);'


