---


- name: create the db users.
  postgresql_user:
   name: "{{ item.name }}"
   password: "{{ item.password }}"
   role_attr_flags: "{{ item.roles }}"
  with_items: "{{ created_users }}"
  become: yes
  become_user: postgres

#
# - name: GRANT ALL PRIVILEGES ON SCHEMA public TO maas_admin
#   postgresql_privs: >
#     db=developer_ems
#     privs=ALL
#     type=schema
#     objs=public
#     role=maas_admin
#
- name: add pg_trgm.
  postgresql_ext:
    name: pg_trgm
    db: template1
    login_host: localhost
    login_password: postgres
    login_user: postgres
  become: yes
  become_user: postgres

- name: create the EMS db
  postgresql_db: name=developer_ems
                 encoding='UTF-8'
                 template='template0'
  become: yes
  become_user: postgres

  #
  # - name: set wal_level to hot_standby in postgresql.conf
  #   pg_config:
  #     name: wal_level
  #     value: minimal
  #     state: present
  #   become: yes
  #   become_user: postgres
