---


- name: create the db users.
  postgresql_user:
   name: "{{ item.name }}"
   password: "{{ item.password }}"
   role_attr_flags: "{{ item.roles }}"
  with_items: "{{ created_users }}"

#
# - name: GRANT ALL PRIVILEGES ON SCHEMA public TO maas_admin
#   postgresql_privs: >
#     db=developer_ems
#     privs=ALL
#     type=schema
#     objs=public
#     role=maas_admin
#
- name: add pg_trgm.
  postgresql_ext:
    name: pg_trgm
    db: template1

- name: create the EMS db
  postgresql_db: name=developer_ems
                 encoding='UTF-8'
                 template='template1'

  #
  # - name: set wal_level to hot_standby in postgresql.conf
  #   pg_config:
  #     name: wal_level
  #     value: minimal
  #     state: present
  #   become: yes
  #   become_user: postgres

# add powa libs:
# wget https://github.com/dalibo/powa-archivist/archive/REL_3_0_0.tar.gz
# shared_preload_libraries='pg_stat_statements,powa,pg_stat_kcache,pg_qualstats'
# psql -U postgres -f install_all.sql
# CREATE DATABASE
# You are now connected to database "powa" as user "postgres".
