---

- name: casandra rolling restart
  hosts: cass42 
  remote_user: jonyc
  serial: 1
  become: yes
  become_user: root
  tasks:
    - name: chmod the script
      file:
        path: /opt/wixpress/dbutils/cassandra/restart-node.sh 
        mode: 0755
    - name: clear the node and drain
      command: /opt/wixpress/dbutils/cassandra/restart-node.sh {{ ansible_eth0.ipv4.address }}
      register: result
    - debug:
        var: result
        verbosity: 1
