---

- name: Clean all repositoies files
  shell: rm -rf /etc/yum.repos.d/*

- name: copy yum.repos folder
  copy:
    src: yum.repos.d/
    dest: "/etc/yum.repos.d/"
    owner: root
    group: root
    mode: 0755

- name: copy pip.conf
  copy:
    src: pip.conf
    dest: "/etc/pip.conf"
    owner: root
    group: root
    mode: 0755
