---

- name: Clean all repositoies files
  shell: rm -rf /etc/yum.repo.d/*

- name: copy yum.repo folder
  copy:
    src: yum.repo.d/
    dest: "/etc/yum.repo.d/"
    owner: root
    group: root
    mode: 0755
