---
# file: roles/common/tasks/main.yml

- include: add_yum_repos.yml
  tags: [host]
  
- include: host.yml
  tags: [host]

- name: Install the common packages
  package: name={{ item }} state=latest
  with_items: "{{ common_packages }}"

- name: disable selinux
  selinux: state=disabled

- name: start chrony
  systemd:
    name: chronyd
    state: started
    daemon_reload: yes
