---
# file: roles/common/tasks/main.yml

- include: host.yml
  tags: [host]

- name: Install the common packages
  package: name={{ item }} state=latest
  with_items: "{{ common_packages }}"
   - libselinux-python
   - chrony

- name: disable selinux
  selinux: state=disabled

- name: start chrony
  systemd:
    name: chrony
    state: started
    daemon_reload: yes
