---

- name: Pring host
  debug:
    var: host
  
- name: Pring host
  debug:
    var: hosts[host]

- name: Pring host
  debug:
    var: subnet_id

- name: "Create new EC2 hosts"
  ec2:
    # aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    # aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    group: "{{ hosts[item].aws_groups | default([]) }}"
    key_name: mgmt-eu
    exact_count: "{{ hosts[item].aws_count | default(1)}}"
    count_tag:
      global_id: "{{ farm_name }}_{{ item }}"
    region: "{{ hosts[item].aws_region }}"
    instance_type: "{{ hosts[item].aws_scale }}"
    image: "{{ hosts[item].aws_ami_id }}"
    volumes: "{{ hosts[item].volumes }}"
    wait: yes
    wait_timeout: 500
    ebs_optimized: "{{ hosts[item].ebs_optimized | default(false) }}"
    instance_initiated_shutdown_behavior: "{{ shutdown_behavior | default('stop') }}"
    instance_tags:
        Name: pavel-test
        farm: "{{ farm_name }}"
        app: "{{ item }}"
        global_id: "{{ farm_name }}_{{ item }}"
        just_created: true
    monitoring: no
    vpc_subnet_id: "{{ subnet_id }}"                  # Subnet id (no name, only id)
    assign_public_ip: "{{ hosts[item].assign_ip | default('no') }}"                # Public access [yes/no]
  register: ec2_infra_host_deploy_result
  with_items: "{{ hosts }}"
  tags:
    - create